In [124]:
import pandas as pd
import numpy as np

In [166]:
df=pd.read_excel("school_data.xlsx")

In [167]:
df

,Class,Boys,Girls,Total,Girls %,Boys %,Gender Gap,Kabaddi Boys,Kabaddi Girls,Kabaddi Level,...,Category (General),Category (SC/OBC),Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,LKG,6.0,10.0,16.0,0.6250,0.3750,-4.0,0.0,0.0,NaN,...,3.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Nursery,5.0,1.0,6.0,0.1667,0.8333,4.0,0.0,0.0,NaN,...,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,UKG,9.0,12.0,21.0,0.5714,0.4286,-3.0,0.0,0.0,NaN,...,3.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,I,14.0,18.0,32.0,0.5625,0.4375,-4.0,10.0,10.0,School,...,3.0,29.0,NaN,NaN,Class,Boys,Girls,Total Students,Girls %,Gender Gap
4,II,14.0,11.0,25.0,0.4400,0.5600,3.0,7.0,10.0,School,...,2.0,23.0,NaN,NaN,LKG,6,10,16,0.625,-4
5,III,12.0,16.0,28.0,0.5714,0.4286,-4.0,7.0,10.0,School,...,4.0,24.0,NaN,NaN,Nursery,5,1,6,0.1667,4
6,IV,11.0,12.0,23.0,0.5217,0.4783,-1.0,6.0,3.0,District,...,2.0,21.0,NaN,NaN,UKG,9,12,21,0.5714,-3
7,V,18.0,12.0,30.0,0.4000,0.6000,6.0,3.0,2.0,State,...,3.0,27.0,NaN,NaN,1st,14,18,32,0.5625,-4
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2nd,14,11,25,0.44,3
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3rd,12,16,28,0.5714,-4
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4th,11,12,23,0.5217,-1
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5th,18,12,30,0.4,6

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Class                  8 non-null      object
 1   Boys                   8 non-null      float64
 2   Girls                  8 non-null      float64
 3   Total                  8 non-null      float64
 4   Girls %                8 non-null      float64
 5   Boys %                 8 non-null      float64
 6   Gender Gap             8 non-null      float64
 7   Kabaddi Boys           8 non-null      float64
 8   Kabaddi Girls          8 non-null      float64
 9   Kabaddi Level          5 non-null      object
 10  Kho-Kho Players Girls  8 non-null      float64
 11  Kho-Kho Players Boys   8 non-null      float64
 12  Kho-Kho Level          5 non-null      object
 13  Category (General)     8 non-null      float64
 14  Category (SC/OBC)      8 non-null      float64
 15  Unnamed: 15            0 non-null      float64
 16  Unnamed: 16            0 non-null      float64
 17  Unnamed: 17            9 non-null      object
 18  Unnamed: 18            9 non-null      object
 19  Unnamed: 19            9 non-null      object
 20  Unnamed: 20            9 non-null      object
 21  Unnamed: 21            9 non-null      object
 22  Unnamed: 22            9 non-null      object
dtypes: float64(14), object(9)
memory usage: 2.3+ KB

In [169]:
df.columns

Index(['Class', 'Boys', 'Girls', 'Total', 'Girls %', 'Boys %', 'Gender Gap',
       'Kabaddi Boys', 'Kabaddi Girls', 'Kabaddi Level',
       'Kho-Kho Players Girls', 'Kho-Kho Players Boys', 'Kho-Kho Level',
       'Category (General)', 'Category (SC/OBC)', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22'],
      dtype='object')

In [170]:
df1= df[['Class', 'Boys', 'Girls', 'Total', 'Girls %', 'Boys %', 'Gender Gap',
       'Kabaddi Boys', 'Kabaddi Girls', 'Kabaddi Level',
       'Kho-Kho Players Girls', 'Kho-Kho Players Boys', 'Kho-Kho Level',
       'Category (General)', 'Category (SC/OBC)']]

In [171]:
df1

,Class,Boys,Girls,Total,Girls %,Boys %,Gender Gap,Kabaddi Boys,Kabaddi Girls,Kabaddi Level,Kho-Kho Players Girls,Kho-Kho Players Boys,Kho-Kho Level,Category (General),Category (SC/OBC)
0,LKG,6.0,10.0,16.0,0.6250,0.3750,-4.0,0.0,0.0,NaN,0.0,0.0,NaN,3.0,13.0
1,Nursery,5.0,1.0,6.0,0.1667,0.8333,4.0,0.0,0.0,NaN,0.0,0.0,NaN,2.0,4.0
2,UKG,9.0,12.0,21.0,0.5714,0.4286,-3.0,0.0,0.0,NaN,0.0,0.0,NaN,3.0,18.0
3,I,14.0,18.0,32.0,0.5625,0.4375,-4.0,10.0,10.0,School,12.0,12.0,School,3.0,29.0
4,II,14.0,11.0,25.0,0.4400,0.5600,3.0,7.0,10.0,School,12.0,12.0,School,2.0,23.0
5,III,12.0,16.0,28.0,0.5714,0.4286,-4.0,7.0,10.0,School,12.0,9.0,School,4.0,24.0
6,IV,11.0,12.0,23.0,0.5217,0.4783,-1.0,6.0,3.0,District,5.0,7.0,District,2.0,21.0
7,V,18.0,12.0,30.0,0.4000,0.6000,6.0,3.0,2.0,State,2.0,4.0,State,3.0,27.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [172]:
df1=df1.dropna(how='all')

In [173]:
df1

,Class,Boys,Girls,Total,Girls %,Boys %,Gender Gap,Kabaddi Boys,Kabaddi Girls,Kabaddi Level,Kho-Kho Players Girls,Kho-Kho Players Boys,Kho-Kho Level,Category (General),Category (SC/OBC)
0,LKG,6.0,10.0,16.0,0.6250,0.3750,-4.0,0.0,0.0,NaN,0.0,0.0,NaN,3.0,13.0
1,Nursery,5.0,1.0,6.0,0.1667,0.8333,4.0,0.0,0.0,NaN,0.0,0.0,NaN,2.0,4.0
2,UKG,9.0,12.0,21.0,0.5714,0.4286,-3.0,0.0,0.0,NaN,0.0,0.0,NaN,3.0,18.0
3,I,14.0,18.0,32.0,0.5625,0.4375,-4.0,10.0,10.0,School,12.0,12.0,School,3.0,29.0
4,II,14.0,11.0,25.0,0.4400,0.5600,3.0,7.0,10.0,School,12.0,12.0,School,2.0,23.0
5,III,12.0,16.0,28.0,0.5714,0.4286,-4.0,7.0,10.0,School,12.0,9.0,School,4.0,24.0
6,IV,11.0,12.0,23.0,0.5217,0.4783,-1.0,6.0,3.0,District,5.0,7.0,District,2.0,21.0
7,V,18.0,12.0,30.0,0.4000,0.6000,6.0,3.0,2.0,State,2.0,4.0,State,3.0,27.0

In [174]:
df1.fillna('None', inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14476\800137903.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.fillna('None', inplace=True)

In [175]:
df1

,Class,Boys,Girls,Total,Girls %,Boys %,Gender Gap,Kabaddi Boys,Kabaddi Girls,Kabaddi Level,Kho-Kho Players Girls,Kho-Kho Players Boys,Kho-Kho Level,Category (General),Category (SC/OBC)
0,LKG,6.0,10.0,16.0,0.6250,0.3750,-4.0,0.0,0.0,None,0.0,0.0,None,3.0,13.0
1,Nursery,5.0,1.0,6.0,0.1667,0.8333,4.0,0.0,0.0,None,0.0,0.0,None,2.0,4.0
2,UKG,9.0,12.0,21.0,0.5714,0.4286,-3.0,0.0,0.0,None,0.0,0.0,None,3.0,18.0
3,I,14.0,18.0,32.0,0.5625,0.4375,-4.0,10.0,10.0,School,12.0,12.0,School,3.0,29.0
4,II,14.0,11.0,25.0,0.4400,0.5600,3.0,7.0,10.0,School,12.0,12.0,School,2.0,23.0
5,III,12.0,16.0,28.0,0.5714,0.4286,-4.0,7.0,10.0,School,12.0,9.0,School,4.0,24.0
6,IV,11.0,12.0,23.0,0.5217,0.4783,-1.0,6.0,3.0,District,5.0,7.0,District,2.0,21.0
7,V,18.0,12.0,30.0,0.4000,0.6000,6.0,3.0,2.0,State,2.0,4.0,State,3.0,27.0

In [176]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 7
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Class                  8 non-null      object
 1   Boys                   8 non-null      float64
 2   Girls                  8 non-null      float64
 3   Total                  8 non-null      float64
 4   Girls %                8 non-null      float64
 5   Boys %                 8 non-null      float64
 6   Gender Gap             8 non-null      float64
 7   Kabaddi Boys           8 non-null      float64
 8   Kabaddi Girls          8 non-null      float64
 9   Kabaddi Level          8 non-null      object
 10  Kho-Kho Players Girls  8 non-null      float64
 11  Kho-Kho Players Boys   8 non-null      float64
 12  Kho-Kho Level          8 non-null      object
 13  Category (General)     8 non-null      float64
 14  Category (SC/OBC)      8 non-null      float64
dtypes: float64(12), object(3)
memory usage: 1.0+ KB

In [177]:
df1.columns

Index(['Class', 'Boys', 'Girls', 'Total', 'Girls %', 'Boys %', 'Gender Gap',
       'Kabaddi Boys', 'Kabaddi Girls', 'Kabaddi Level',
       'Kho-Kho Players Girls', 'Kho-Kho Players Boys', 'Kho-Kho Level',
       'Category (General)', 'Category (SC/OBC)'],
      dtype='object')

In [178]:
df1[['Boys', 'Girls', 'Total']]=df1[['Boys', 'Girls', 'Total']].astype(int)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14476\952988559.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[['Boys', 'Girls', 'Total']]=df1[['Boys', 'Girls', 'Total']].astype(int)

In [179]:
df1

,Class,Boys,Girls,Total,Girls %,Boys %,Gender Gap,Kabaddi Boys,Kabaddi Girls,Kabaddi Level,Kho-Kho Players Girls,Kho-Kho Players Boys,Kho-Kho Level,Category (General),Category (SC/OBC)
0,LKG,6,10,16,0.6250,0.3750,-4.0,0.0,0.0,None,0.0,0.0,None,3.0,13.0
1,Nursery,5,1,6,0.1667,0.8333,4.0,0.0,0.0,None,0.0,0.0,None,2.0,4.0
2,UKG,9,12,21,0.5714,0.4286,-3.0,0.0,0.0,None,0.0,0.0,None,3.0,18.0
3,I,14,18,32,0.5625,0.4375,-4.0,10.0,10.0,School,12.0,12.0,School,3.0,29.0
4,II,14,11,25,0.4400,0.5600,3.0,7.0,10.0,School,12.0,12.0,School,2.0,23.0
5,III,12,16,28,0.5714,0.4286,-4.0,7.0,10.0,School,12.0,9.0,School,4.0,24.0
6,IV,11,12,23,0.5217,0.4783,-1.0,6.0,3.0,District,5.0,7.0,District,2.0,21.0
7,V,18,12,30,0.4000,0.6000,6.0,3.0,2.0,State,2.0,4.0,State,3.0,27.0

In [180]:
df1.loc[:, 'Girls %'] = (df1['Girls'] / df1['Total']) * 100

In [181]:
df1

,Class,Boys,Girls,Total,Girls %,Boys %,Gender Gap,Kabaddi Boys,Kabaddi Girls,Kabaddi Level,Kho-Kho Players Girls,Kho-Kho Players Boys,Kho-Kho Level,Category (General),Category (SC/OBC)
0,LKG,6,10,16,62.500000,0.3750,-4.0,0.0,0.0,None,0.0,0.0,None,3.0,13.0
1,Nursery,5,1,6,16.666667,0.8333,4.0,0.0,0.0,None,0.0,0.0,None,2.0,4.0
2,UKG,9,12,21,57.142857,0.4286,-3.0,0.0,0.0,None,0.0,0.0,None,3.0,18.0
3,I,14,18,32,56.250000,0.4375,-4.0,10.0,10.0,School,12.0,12.0,School,3.0,29.0
4,II,14,11,25,44.000000,0.5600,3.0,7.0,10.0,School,12.0,12.0,School,2.0,23.0
5,III,12,16,28,57.142857,0.4286,-4.0,7.0,10.0,School,12.0,9.0,School,4.0,24.0
6,IV,11,12,23,52.173913,0.4783,-1.0,6.0,3.0,District,5.0,7.0,District,2.0,21.0
7,V,18,12,30,40.000000,0.6000,6.0,3.0,2.0,State,2.0,4.0,State,3.0,27.0

In [182]:
df1['Girls %']=df1['Girls %'].round()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14476\2757928527.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Girls %']=df1['Girls %'].round()

df1

In [183]:
df1

,Class,Boys,Girls,Total,Girls %,Boys %,Gender Gap,Kabaddi Boys,Kabaddi Girls,Kabaddi Level,Kho-Kho Players Girls,Kho-Kho Players Boys,Kho-Kho Level,Category (General),Category (SC/OBC)
0,LKG,6,10,16,62.0,0.3750,-4.0,0.0,0.0,None,0.0,0.0,None,3.0,13.0
1,Nursery,5,1,6,17.0,0.8333,4.0,0.0,0.0,None,0.0,0.0,None,2.0,4.0
2,UKG,9,12,21,57.0,0.4286,-3.0,0.0,0.0,None,0.0,0.0,None,3.0,18.0
3,I,14,18,32,56.0,0.4375,-4.0,10.0,10.0,School,12.0,12.0,School,3.0,29.0
4,II,14,11,25,44.0,0.5600,3.0,7.0,10.0,School,12.0,12.0,School,2.0,23.0
5,III,12,16,28,57.0,0.4286,-4.0,7.0,10.0,School,12.0,9.0,School,4.0,24.0
6,IV,11,12,23,52.0,0.4783,-1.0,6.0,3.0,District,5.0,7.0,District,2.0,21.0
7,V,18,12,30,40.0,0.6000,6.0,3.0,2.0,State,2.0,4.0,State,3.0,27.0

In [184]:
df1.loc[:,'Boys %']= (df1['Boys'] / df1['Total']) * 100

In [185]:
df1

,Class,Boys,Girls,Total,Girls %,Boys %,Gender Gap,Kabaddi Boys,Kabaddi Girls,Kabaddi Level,Kho-Kho Players Girls,Kho-Kho Players Boys,Kho-Kho Level,Category (General),Category (SC/OBC)
0,LKG,6,10,16,62.0,37.500000,-4.0,0.0,0.0,None,0.0,0.0,None,3.0,13.0
1,Nursery,5,1,6,17.0,83.333333,4.0,0.0,0.0,None,0.0,0.0,None,2.0,4.0
2,UKG,9,12,21,57.0,42.857143,-3.0,0.0,0.0,None,0.0,0.0,None,3.0,18.0
3,I,14,18,32,56.0,43.750000,-4.0,10.0,10.0,School,12.0,12.0,School,3.0,29.0
4,II,14,11,25,44.0,56.000000,3.0,7.0,10.0,School,12.0,12.0,School,2.0,23.0
5,III,12,16,28,57.0,42.857143,-4.0,7.0,10.0,School,12.0,9.0,School,4.0,24.0
6,IV,11,12,23,52.0,47.826087,-1.0,6.0,3.0,District,5.0,7.0,District,2.0,21.0
7,V,18,12,30,40.0,60.000000,6.0,3.0,2.0,State,2.0,4.0,State,3.0,27.0

In [186]:
df1['Boys %']=df1['Boys %'].round()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14476\3789844011.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Boys %']=df1['Boys %'].round()

In [187]:
df1

,Class,Boys,Girls,Total,Girls %,Boys %,Gender Gap,Kabaddi Boys,Kabaddi Girls,Kabaddi Level,Kho-Kho Players Girls,Kho-Kho Players Boys,Kho-Kho Level,Category (General),Category (SC/OBC)
0,LKG,6,10,16,62.0,38.0,-4.0,0.0,0.0,None,0.0,0.0,None,3.0,13.0
1,Nursery,5,1,6,17.0,83.0,4.0,0.0,0.0,None,0.0,0.0,None,2.0,4.0
2,UKG,9,12,21,57.0,43.0,-3.0,0.0,0.0,None,0.0,0.0,None,3.0,18.0
3,I,14,18,32,56.0,44.0,-4.0,10.0,10.0,School,12.0,12.0,School,3.0,29.0
4,II,14,11,25,44.0,56.0,3.0,7.0,10.0,School,12.0,12.0,School,2.0,23.0
5,III,12,16,28,57.0,43.0,-4.0,7.0,10.0,School,12.0,9.0,School,4.0,24.0
6,IV,11,12,23,52.0,48.0,-1.0,6.0,3.0,District,5.0,7.0,District,2.0,21.0
7,V,18,12,30,40.0,60.0,6.0,3.0,2.0,State,2.0,4.0,State,3.0,27.0

In [199]:
df1[['Kho-Kho Players Girls', 'Kho-Kho Players Boys']]=df1[['Kho-Kho Players Girls', 'Kho-Kho Players Boys']].astype(int)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14476\172943456.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[['Kho-Kho Players Girls', 'Kho-Kho Players Boys']]=df1[['Kho-Kho Players Girls', 'Kho-Kho Players Boys']].astype(int)

In [200]:
df1[['Category (General)', 'Category (SC/OBC)']] = df1[['Category (General)', 'Category (SC/OBC)']].astype(int)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14476\4141271198.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[['Category (General)', 'Category (SC/OBC)']] = df1[['Category (General)', 'Category (SC/OBC)']].astype(int)

In [201]:
df1

,Class,Boys,Girls,Total,Girls %,Boys %,Gender Gap,Kabaddi Boys,Kabaddi Girls,Kabaddi Level,Kho-Kho Players Girls,Kho-Kho Players Boys,Kho-Kho Level,Category (General),Category (SC/OBC)
0,LKG,6,10,16,62.0,38.0,-4,0,0,None,0,0,None,3,13
1,Nursery,5,1,6,17.0,83.0,4,0,0,None,0,0,None,2,4
2,UKG,9,12,21,57.0,43.0,-3,0,0,None,0,0,None,3,18
3,I,14,18,32,56.0,44.0,-4,10,10,School,12,12,School,3,29
4,II,14,11,25,44.0,56.0,3,7,10,School,12,12,School,2,23
5,III,12,16,28,57.0,43.0,-4,7,10,School,12,9,School,4,24
6,IV,11,12,23,52.0,48.0,-1,6,3,District,5,7,District,2,21
7,V,18,12,30,40.0,60.0,6,3,2,State,2,4,State,3,27

In [202]:
df1.to_csv("PYSchoolData.csv", index=False)